

export const metadata = {
  title: "I am b4: Work",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch data for portfolio
  
  return (
    <div>
      This is the layout file
      {children}
    </div>
  );
}
