import "./globals.css";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

export const metadata = {
  title: "I am b4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
